language: cpp

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

os:
  - osx

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - BUILD_TYPE=Debug
        - DISTRIBUTION_VARIANT=linux_gcc5_debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - BUILD_TYPE=Release
        - DISTRIBUTION_VARIANT=linux_gcc5_release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Debug
        - DISTRIBUTION_VARIANT=linux_clang_debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Release
        - DISTRIBUTION_VARIANT=linux_clang_release

    - language: android
      jdk: oraclejdk8
      os: linux

      env:
        global:
          - ANDROID=true
          - ANDROID_API_LEVEL=21
          - EMULATOR_API_LEVEL=21
          - ANDROID_BUILD_TOOLS=26.1.1
          - ADB_INSTALL_TIMEOUT=5 # minutes
          - DISTRIBUTION_VARIANT=android_release

      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-${ANDROID_BUILD_TOOLS}
          - android-${ANDROID_API_LEVEL}
          - extra # ???
          - add-on # ???
      #    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

      install:
        # Accept SDK Licenses + Install NDK
        - yes | sdkmanager --update > /dev/null
        - sdkmanager ndk-bundle > /dev/null
          # Install the system image.
        # [DISABLED] Setting up AVD and starting an emulator
        # - sdkmanager "system-images;android-24;default;armeabi-v7a" > /dev/null
        # # Create and start emulator for the script. Meant to race the install task.
        # - android list target
        # - avdmanager list avd
        # - echo no | avdmanager create avd --force -n test_AVD -k "system-images;android-24;default;armeabi-v7a"
        # - android list target
        # - avdmanager list avd
        # - $ANDROID_HOME/emulator/emulator -avd test_AVD -no-audio -no-window &

      script:
        - set -e
        - cd ./samples/android_run_tests/
        - ./gradlew assembleRelease
      # [DISABLED] installing apk on emulator
      #  - android-wait-for-emulator
      #  - adb shell input keyevent 82 &
      #  - adb devices
      #  - ./gradlew installRelease --stacktrace --debug

    - language: objective-c
      os: osx

      script:
        - export BUILD_DIR=$(pwd)/build-iOS
        - mkdir ${BUILD_DIR} && pushd ${BUILD_DIR}

        # Prepare && build
        - cmake ..  -G'Unix Makefiles' -DCCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../tools/ios-cmake/ios.toolchain.cmake -DIOS_PLATFORM=OS -DIOS_DEPLOYMENT_TARGET=9.0 -DCMAKE_OSX_ARCHITECTURES=arm64 -DMULTY_WITH_TESTS=1 -DMULTY_WITH_ALL_BLOCKCHAINS=ON
        - cmake --build .

        # Copy build artifacts to the sample app
        - find . -iname '*.dylib' -or -iname '*.a' -not -path '*google*' -exec cp {} ../samples/iOS_run_tests/Libraries/ \;

        # Copy headers to the sample app
        - cp ../multy_core/*.h ../samples/iOS_run_tests/Headers

        # Update Headers: Rename Error to MultyError due to name clash.
        - sed -i '' -E 's/Error/MultyError/g' ../samples/iOS_run_tests/Headers/error.h
      env:
        - DISTRIBUTION_VARIANT=osx_release

        # Build the sample app with updated libs and headers
        #  - xcodebuild -list -project ../samples/iOS_run_tests/iOS_run_tests.xcodeproj
        #  - xcodebuild build -configuration Debug -project ../samples/iOS_run_tests/iOS_run_tests.xcodeproj #CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

before_script:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  # TODO: split in multiple lines
  - cmake .. -G'Unix Makefiles' -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMULTY_MORE_WARNINGS=ON -DMULTY_TEST_DISABLE_DEATH_TESTS=ON -DMULTY_WARNINGS_AS_ERRORS=ON -DMULTY_WITH_TESTS=ON -DMULTY_WITH_TEST_APP=ON -DMULTY_WITH_ALL_BLOCKCHAINS=ON
  - cmake --build . --target all
  - ./multy

before_deploy:
  - echo 'ABOUT TO DEPLOY!!!! WOOOHOOO!!!' && pwd
  - export DISTRIBUTION_VARIANT=${DISTRIBUTION_VARIANT:+${TRAVIS_OS_NAME}_${BUILD_TYPE}}
  - export DISTRIBUTION_VERSION=${TRAVIS_TAG:+${TRAVIS_COMMIT}}
  - export DISTRIBUTION_NAME=distribution_${DISTRIBUTION_VARIANT}_${DISTRIBUTION_VERSION}.zip
  - mkdir -p ./distribution ./distribution/bin ./distribution/include
  - find . \( -iname '*.a' -o -iname '*.so' -o -iname '*.dlyb' \) -a \( -iname '*multy_core*' -o -iname '*ccan*' -o -iname '*keccak*' -o -iname '*mini-gmp*' -o -iname '*jsoncpp*' -not -name '*.o' \) -not -path '*google*' -type f -exec cp {} ./distribution/bin \;
  - cp ../multy_core/*.h ./distribution/include
  - cp ../LICENSE ./distribution
  - "printf \"Branch: $(git rev-parse --abbrev-ref HEAD)\nCommit: $(git log -1 --format=%h)\nTag: $(git describe --tags --abbrev=0 --dirty --candidates=0)\" > ./distribution/VERSION"
  - tar czf ${DISTRIBUTION_NAME} ./distribution
  - pwd && echo ${DISTRIBUTION_NAME}
  - tar -tf ${DISTRIBUTION_NAME}

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  overwrite: true
  # do as Enmk
  api_key:
    secure: "Ka87RA3kWWvmJWDG3Y7zAoSGPZsd8dA/QiL/jNZ1rxBmpZfw96yYTFHJKK5vuPpyouQ8bHLxLKiGi3XB6RQ8X0mhfMlCnjqwVOOYVgwKjaIj+o0vCjpE/3NjpWwzAZt6ZjoVxb0wQVIxs68GZXoAyj+pUNCNXR2yGOEVfnhx2+wRCtqFpkZeyDfDb/ZppI1sYrxjt0ezOqtWoKt2OQYnjCb/bam5dVQqlRT15ac9uZ2ak0/BomqnpMC/sztzrWZZL9/B358XfGkZ+prCqWZKX1buJ7hRzG5nNgWpPQvIBnuP/4p/UBO4L+zy/fk8XE1V6rVEYw3q5IaUyB01nhYI4Vz50yTK/LW83oVmIsmVqXNAz71/Ud6mjUGUW3xewEpoc+jlGEgxlqkW/mKZW1muiyh7rECD/c2jcHK40+zgIBOpov1tqNZqJ3cHbRcmRs49WklPiF7UQ/DNCvJTbNVZ0Qj2HhEGW56VOIqX4SxFS0gRXk9QrfGTgJI6uTKzT/ZSjmRLLqmfAkcRn6opRYMASwDjNvJMEqLyHEC7jiH7YaUVVRYqvciwC+/nju1bexweOqyD6CDGs2sTsXbP9VeXUi9SRnwVsuiaaTaPKwDJY9dC8qM5Z6dAm0RjMdv23gwFTjYLWfmaOQ5U8tysDiKS+1TXtoOVcJOl+LgJNbmBog4="
  file: "${DISTRIBUTION_NAME}"
  on:
#    tags: true
#    repo: Multy-io/Multy-back
    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^v\d+.\d+$
