language: cpp

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

os:
  - osx

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Release

    - language: android
      jdk: oraclejdk8
      os: linux

      env:
        global:
          - ANDROID=true
          - ANDROID_API_LEVEL=21
          - EMULATOR_API_LEVEL=21
          - ANDROID_BUILD_TOOLS=26.1.1
          - ADB_INSTALL_TIMEOUT=5 # minutes

      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-${ANDROID_BUILD_TOOLS}
          - android-${ANDROID_API_LEVEL}
          - extra # ???
          - add-on # ???
      #    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

      install:
        # Accept SDK Licenses + Install NDK
        - yes | sdkmanager --update > /dev/null
        - sdkmanager ndk-bundle > /dev/null
          # Install the system image.
        # [DISABLED] Setting up AVD and starting an emulator
        # - sdkmanager "system-images;android-24;default;armeabi-v7a" > /dev/null
        # # Create and start emulator for the script. Meant to race the install task.
        # - android list target
        # - avdmanager list avd
        # - echo no | avdmanager create avd --force -n test_AVD -k "system-images;android-24;default;armeabi-v7a"
        # - android list target
        # - avdmanager list avd
        # - $ANDROID_HOME/emulator/emulator -avd test_AVD -no-audio -no-window &

      script:
        - set -e
        - cd ./samples/android_run_tests/
        - ./gradlew assembleRelease
      # [DISABLED] installing apk on emulator
      #  - android-wait-for-emulator
      #  - adb shell input keyevent 82 &
      #  - adb devices
      #  - ./gradlew installRelease --stacktrace --debug

    - language: objective-c
      os: osx

      script:
        - export BUILD_DIR=$(pwd)/build-iOS
        - mkdir ${BUILD_DIR} && pushd ${BUILD_DIR}

        # Prepare && build
        - cmake ..  -G'Unix Makefiles' -DCCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../tools/ios-cmake/ios.toolchain.cmake -DIOS_PLATFORM=OS -DIOS_DEPLOYMENT_TARGET=9.0 -DCMAKE_OSX_ARCHITECTURES=arm64 -DMULTY_WITH_TESTS=1 -DMULTY_WITH_ALL_BLOCKCHAINS=ON
        - cmake --build .

        # Copy build artifacts to the sample app
        - find . -iname '*.dylib' -or -iname '*.a' -not -path '*google*' -exec cp {} ../samples/iOS_run_tests/Libraries/ \;

        # Copy headers to the sample app
        - cp ../multy_core/*.h ../samples/iOS_run_tests/Headers

        # Update Headers: Rename Error to MultyError due to name clash.
        - sed -i '' -E 's/Error/MultyError/g' ../samples/iOS_run_tests/Headers/error.h

        # Build the sample app with updated libs and headers
        #  - xcodebuild -list -project ../samples/iOS_run_tests/iOS_run_tests.xcodeproj
        #  - xcodebuild build -configuration Debug -project ../samples/iOS_run_tests/iOS_run_tests.xcodeproj #CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

before_script:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  # TODO: split in multiple lines
  - cmake .. -G'Unix Makefiles' -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMULTY_MORE_WARNINGS=ON -DMULTY_TEST_DISABLE_DEATH_TESTS=ON -DMULTY_WARNINGS_AS_ERRORS=ON -DMULTY_WITH_TESTS=ON -DMULTY_WITH_TEST_APP=ON -DMULTY_WITH_ALL_BLOCKCHAINS=ON
  - cmake --build . --target all
  - ./multy

before_deploy:
  - echo 'ABOUT TO DEPLOY!!!! WOOOHOOO!!!' && find . -iname '*multy*'
  - mkdir -p ./distribution ./distribution/bin ./distribution/include
  - find . -iname '*multy_core*' -iname '*ccan*' -iname '*keccak*' -iname '*mini-gmp*' -iname '*jsoncpp*' -not -name '*.o' -not -path '*google*' -exec cp {} ./distribution/bin \;
  - cp ../multy_core/*.h ./distribution/include
  - tar czf distribution.zip ./distribution

deploy:
  skip_cleanup: true
  draft: true
  provider: releases
  api_key:
    secure: ODD5Q6V4qVdv96IgaS+pBVRKtNFih905Uv9IoWE1JCfuc2bOz2zqUbhD4+z6KMLJvD0QLlWBMWl+pDsAE+iOKAwQ7TnwjXoE79D3eSqk83WGraBej5Jlh6qiMoqcjBdAAkUr9BBDe4XS906dD65wEaVxZi9yHOkoK2gRhP6JwLrA1WaNVYtdvF+wR15537D0OvnttV4b8s3eaiTWwsG/lznyZ3EyeaLK+pdPCDsbvgPZsKilkEp6REimwAdr1Y4Pq99mLLq41Y42rOIu2hxehmnt9hrDPvXj1FHH1cr8/Loba6MNDW4AxvPY1Lez8Sjinhx0KeicqJwXTjqkNI2jgbwJ21phzfEf0Ts2b01OBVFraqEMdP7vW8hXyuXJv4lmZuER4uP7yzYLKX99yHpyyBkUcoB/DV61mAZcoJxHkNq2HTwNlQh35LT/I0lio5WGmDb8FEIieiYkaxQAYeMQpVrIVaX6ADoJGhiERyQ5zyfe4HIVcAmL5ishZZcDrcdAmZf9f0D7l9Dfo4t/mt22BN5kA8VnxEnutb4H9IgNNWlTKSj87nI8Yu+mm36za/g2GtB1eGyHXZ2f5Dv292lpEXL1Aly4AK91YDMtxOjfXTpqrpkFoGgMxJKroR5V6xt4ZwbwAv8KTJvbwE6qgwojgDVH7DQanYDe2ekqE30Fktg=
  file: ''
  on:
#    tags: true
#    repo: Multy-io/Multy-back
    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^v\d+.\d+$
